services:
  db:
    image: mariadb:10.11
    restart: always
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
      MYSQL_DATABASE: postfixadmin
      MYSQL_USER: postfixadmin
      MYSQL_PASSWORD: postfixadminPassword

  dovecot:
    image: dovecot/dovecot:latest
    volumes:
      - ./dovecot.conf:/etc/dovecot/dovecot.conf
      - ./dovecot-sql.conf:/etc/dovecot/dovecot-sql.conf
      - ./data/maildir:/srv/mail

  postfix:
    build: postfix

  postfixadmin:
    depends_on:
      - db
      - dovecot
      - postfix
    image: postfixadmin:latest
    ports:
      - "8082:80"
    restart: always
    volumes:
      - ./config.local.php:/var/www/html/config.local.php